#ifndef __MOTOR_CONTROL_CONFIG_H__
#define __MOTOR_CONTROL_CONFIG_H__

#define PBIO_CONFIG_SERVO_PERIOD_MS (3)

#define MOTOR_PWM_FREQUENCY (9000)
#define MOTOR_PWM_RESOLUTION (12)
#define MOTOR_PWM_MAX_VALUE ((1 << MOTOR_PWM_RESOLUTION) - 2)

#define ENCODER_COUNTS_PER_DEGREE (2)

#define SERIAL_PRINT_MOTOR_ERROR

#endif